[package]
name = "ebpf-sys"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
edition = "2018"

[features]
default = []
gen = ["bindgen"]

[dependencies]
cfg-if = "0.1"

[build-dependencies]
bindgen = { version = "0.49", optional = true }
