[package]
name = "ebpf-loader"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
edition = "2018"

[dependencies]
cfg-if = "0.1"
log = "0.4"
failure = "0.1"
lazy_static = "1.3"
goblin = "0.0.22"
scroll = "0.9"
libc = "0.2"

ebpf-core = { version = "0.1", path = "../ebpf-core" }
