[package]
name = "xdp-runtime"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = []

[dependencies]
ebpf-runtime = { version = "0.1", path = "../ebpf-runtime" }
